In [2]:
import numpy as np

In [9]:
# ques 1 
arr=np.array([1,2,3,6,4,5])
print(np.flip(arr))
#method2
print(arr[::-1])

[5 4 6 3 2 1]
[5 4 6 3 2 1]


In [ ]:
# b part
arr1=np.array([[1,2,3],[2,4,5],[1,2,3]])
flat=arr1.flatten()
print(flat)
print(arr1.ravel())

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


In [ ]:
# c part
arr2=np.array([[1,2],[3,4]])
arr3=np.array([[1,2],[3,4]])
print(arr2==arr3)

[[ True  True]
 [ True  True]]


In [22]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

most_freq = np.bincount(x).argmax()
indices = np.where(x == most_freq)[0]

print("Most frequent value:", most_freq)
print("Indices:", indices)

y = np.array([1,1,1,2,3,4,2,4,3,3,1])

most_freq = np.bincount(y).argmax()
indices = np.where(y == most_freq)[0]

print("Most frequent value:", most_freq)
print("Indices:", indices)

Most frequent value: 1
Indices: [0 5 7 8 9]
Most frequent value: 1
Indices: [ 0  1  2 10]


In [26]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Total sum:", gfg.sum())
print("row:", gfg.sum(axis=1))
print("col:", gfg.sum(axis=0))

Total sum: 45
row: [[14]
 [16]
 [15]]
col: [[20  9 16]]


In [28]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
diagonal_sum = np.trace(n_array)
print("Sum of diagonal elements:", diagonal_sum)
eigen_values= np.linalg.eig(n_array)
print("Eigenvalues:", eigen_values)
eigen_vectors = np.linalg.eig(n_array)
print("Eigenvectors:\n", eigen_vectors)
inverse_matrix = np.linalg.inv(n_array)
print("Inverse of matrix:\n", inverse_matrix)
determinant = np.linalg.det(n_array)
print("Determinant of matrix:", determinant)


Sum of diagonal elements: 176
Eigenvalues: EigResult(eigenvalues=array([98.16835147, 28.097044  , 49.73460452]), eigenvectors=array([[ 0.4574917 ,  0.34637121, -0.15017693],
       [ 0.28447814, -0.72784061, -0.4852124 ],
       [ 0.84248058,  0.59184038,  0.8614034 ]]))
Eigenvectors:
 EigResult(eigenvalues=array([98.16835147, 28.097044  , 49.73460452]), eigenvectors=array([[ 0.4574917 ,  0.34637121, -0.15017693],
       [ 0.28447814, -0.72784061, -0.4852124 ],
       [ 0.84248058,  0.59184038,  0.8614034 ]]))
Inverse of matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of matrix: 137180.0000000001


In [31]:
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
product = np.matmul(p, q)
print("Matrix Multiplication:\n", product)
covariance = np.cov(p.flatten(), q.flatten())
print("Covariance Matrix:\n", covariance)
p = np.array([[1, 2], [2, 3], [4, 5]])
q = np.array([[4, 5, 1], [6, 7, 2]])
product = np.matmul(p, q)
print("Matrix Multiplication:\n", product)
covariance = np.cov(p.flatten(), q.flatten())
print("Covariance Matrix:\n", covariance)


Matrix Multiplication:
 [[16 19]
 [26 31]]
Covariance Matrix:
 [[0.66666667 1.        ]
 [1.         1.66666667]]
Matrix Multiplication:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance Matrix:
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [33]:
x = np.array([[2, 3, 4],[3, 2, 9]])

y = np.array([[1, 5, 0],[5, 10, 3]])
inner = np.inner(x, y)
print("Inner Product:\n", inner)
outer = np.outer(x.flatten(), y.flatten())
print("Outer Product:\n", outer)
from itertools import product
x_flat = x.flatten()
y_flat = y.flatten()

cartesian = np.array(list(product(x_flat, y_flat)))
print("Cartesian Product:\n", cartesian)


Inner Product:
 [[17 52]
 [13 62]]
Outer Product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian Product:
 [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [35]:
#ques2
array = np.array([[1, -2, 3],[-4, 5, -6]])
abs_array = np.abs(array)
print("Absolute Values:\n", abs_array)
p_flat = np.percentile(array, [25, 50, 75])
print("Flattened Percentiles (25, 50, 75):", p_flat)
p_col = np.percentile(array, [25, 50, 75], axis=0)
print("Column-wise Percentiles:\n", p_col)
p_row = np.percentile(array, [25, 50, 75], axis=1)
print("Row-wise Percentiles:\n", p_row)
# Flattened
mean_flat = np.mean(array)
median_flat = np.median(array)
std_flat = np.std(array)

print("Flattened - Mean:", mean_flat, "| Median:", median_flat, "| Std Dev:", std_flat)

# Column-wise
mean_col = np.mean(array, axis=0)
median_col = np.median(array, axis=0)
std_col = np.std(array, axis=0)

print("Column-wise - Mean:", mean_col)
print("Column-wise - Median:", median_col)
print("Column-wise - Std Dev:", std_col)

# Row-wise
mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)

print("Row-wise - Mean:", mean_row)
print("Row-wise - Median:", median_row)
print("Row-wise - Std Dev:", std_row)



Absolute Values:
 [[1 2 3]
 [4 5 6]]
Flattened Percentiles (25, 50, 75): [-3.5 -0.5  2.5]
Column-wise Percentiles:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Row-wise Percentiles:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Flattened - Mean: -0.5 | Median: -0.5 | Std Dev: 3.8622100754188224
Column-wise - Mean: [-1.5  1.5 -1.5]
Column-wise - Median: [-1.5  1.5 -1.5]
Column-wise - Std Dev: [2.5 3.5 4.5]
Row-wise - Mean: [ 0.66666667 -1.66666667]
Row-wise - Median: [ 1. -4.]
Row-wise - Std Dev: [2.05480467 4.78423336]


In [37]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
floor_vals = np.floor(a)
print("Floor:", floor_vals)
ceil_vals = np.ceil(a)
print("Ceiling:", ceil_vals)
trunc_vals = np.trunc(a)
print("Truncated:", trunc_vals)
rounded_vals = np.round(a)
print("Rounded:", rounded_vals)


Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling: [-1. -1. -0.  1.  2.  2.  3.]
Truncated: [-1. -1. -0.  0.  1.  1.  3.]
Rounded: [-2. -2. -0.  0.  2.  2.  3.]


In [39]:
#ques 3
array = np.array([10, 52, 62, 16, 16, 54, 453])
sorted_array = np.sort(array)
print("Sorted array:", sorted_array)
sorted_indices = np.argsort(array)
print("Indices of sorted array:", sorted_indices)
smallest_4 = np.sort(array)[:4]
print("4 smallest elements:", smallest_4)
largest_5 = np.sort(array)[-5:]
print("5 largest elements:", largest_5)


Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [ 16  52  54  62 453]


In [41]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integers_only = array[array == np.floor(array)]
print("Integer elements only:", integers_only)
floats_only = array[array != np.floor(array)]
print("Float elements only:", floats_only)


Integer elements only: [1. 2. 3. 2.]
Float elements only: [1.2 2.2]
